#headers = { Authorization = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWQzbDVheWQwMDAwZGdsaXAwa2cxbmwzIiwiZW1haWwiOiJhZG1pbkBjYXJjb25maWd1cmF0b3IuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUyNTc3ODgzLCJleHAiOjE3NTMxODI2ODN9.jnXPx6kK5dvKp9AiTZlqdTOnJyAwUdD_DkC9f_llrJc" }
#continue-on-failure = true


# [output.sanitization]
# enabled = false

# [generation]
# max-examples = 500

# [reports.junit]
# enabled = true